include(CheckCCompilerFlag)
include(CheckSymbolExists)
if(MSVC)
else()
    check_c_compiler_flag(-Wno-builtin-declaration-mismatch HAS_WNO_BUILTIN_DECLARATION_MISMATCH)
    check_c_compiler_flag(-Wno-incompatible-library-redeclaration HAS_WNO_INCOMPATIBLE_LIBRARY_REDECLARATION)
endif()

function(check_symbols_in_parallel PARALLEL_SUCCESS)
    cmake_parse_arguments(ARG "" "VAR_PREFIX;VAR_SUFFIX" "SYMBOLS" ${ARGN})
    set(non_existing_sym wushiewush)

    if(NOT ARG_SYMBOLS)
        message(FATAL_ERROR "Missing required SYMBOLS")
    endif()
    if(NOT ARG_VAR_PREFIX AND NOT ARG_VAR_SUFFIX)
        message(FATAL_ERROR "At least one of VAR_PREFIX or VAR_SUFFIX must be defined")
    endif()

    set(symbols)
    foreach(symbol IN LISTS ARG_SYMBOLS)
        string(MAKE_C_IDENTIFIER "${symbol}" varname_core)
        string(TOUPPER "${varname_core}" varname_core)
        set(varname "${ARG_VAR_PREFIX}${varname_core}${ARG_VAR_SUFFIX}")
        if(NOT DEFINED "${varname}" AND NOT DEFINED CACHE{${varname}})
            list(APPEND symbols ${symbol})
            message(STATUS "Performing Parallel Linking Test ${varname}")
        endif()
    endforeach()
    if(NOT symbols)
        set(PARALLEL_SUCCESS 1 PARENT_SCOPE)
        return()
    endif()

    set(check_symbols ${symbols} ${non_existing_sym})

    set(decls)
    set(body)
    set(i 1)
    foreach(symbol IN LISTS check_symbols)
        string(APPEND decls "extern void ${symbol}(void);\n")
        string(APPEND body "  if (argv[${i}]) { ${symbol}(); }\n")
        math(EXPR i "${i}+1")
    endforeach()

    set(src_path "${CMAKE_BINARY_DIR}/parse_linker_output.c")
    set(src_body "${decls}\nint main(int argc, char *argv[]) {\n  (void)argc;\n  (void)argv;\n\n${body}\n  return 0;\n}\n")
    file(WRITE "${src_path}" "${src_body}")

    set(check_c_flags "${CMAKE_C_FLAGS}")
    if(HAS_WNO_BUILTIN_DECLARATION_MISMATCH)
        string(APPEND check_c_flags " -Wno-builtin-declaration-mismatch")
    endif()
    if(HAS_WNO_INCOMPATIBLE_LIBRARY_REDECLARATION)
        string(APPEND check_c_flags " -Wno-incompatible-library-redeclaration")
    endif()

    set(CMAKE_TRY_COMPILE_TARGET_TYPE "EXECUTABLE")
#    unset(try_compile_result CACHE)
    try_compile(try_compile_result "${CMAKE_CURRENT_BINARY_DIR}/tt" SOURCES "${src_path}" OUTPUT_VARIABLE try_compile_output NO_CACHE CMAKE_FLAGS "-DCOMPILE_DEFINITIONS=${check_c_flags}" LINK_LIBRARIES "m")

    message(DEBUG "try_compile result: ${try_compile_result}")
    message(DEBUG "try_compile output: START[try_compile output]${try_compile_output}END[try_compile output]")
#    unset(try_compile_result CACHE)

    string(REGEX MATCHALL "\n[^\n]*[:]([^\n]*${non_existing_sym}[^\n]*)\n" missing_symbol_error "${try_compile_output}")
    if(NOT missing_symbol_error)
        message(WARNING "Parallel symbol detection using linker does not work")
        message(WARNING "output is START ${try_compile_output} END")
        set(PARALLEL_SUCCESS 0 PARENT_SCOPE)
        message(FATAL_ERROR "WUT")
        return()
    endif()
    set(re_missing_symbol_error "${CMAKE_MATCH_1}")
    message(DEBUG  "missing symbol error (before clean-up): ${re_missing_symbol_error}")
    string(REGEX REPLACE "(\\(|\\)|\\.|\\||\\[|\\])" "[\\1]" re_missing_symbol_error "${re_missing_symbol_error}")
    message(DEBUG "missing symbol error (after clean-up): ${re_missing_symbol_error}")

    foreach(symbol IN LISTS symbols)
        string(MAKE_C_IDENTIFIER "${symbol}" varname_core)
        string(TOUPPER "${varname_core}" varname_core)
        set(varname "${ARG_VAR_PREFIX}${varname_core}${ARG_VAR_SUFFIX}")
        string(REPLACE "${non_existing_sym}" "${symbol}" new_re "${re_missing_symbol_error}")
        string(FIND "${try_compile_output}" "${new_re}" pos_re)
        if(pos_re LESS 0)
            set(result "1")
            set(result_str "Success")
        else()
            set(result "")
            set(result_str "Failed")
        endif()
        message(DEBUG "varname=${varname} re=\"${new_re}\" result=${result} pos_re=${pos_re}")
        string(MAKE_C_IDENTIFIER "${symbol}" varname_core)
        string(TOUPPER "${varname_core}" varname_core)
        set("${varname}" "${result}" CACHE INTERNAL "Test ${varname}")
        message(STATUS "Performing Parallel Linking Test ${varname} - ${result_str}")
    endforeach()
    set(${PARALLEL_SUCCESS} 1 PARENT_SCOPE)
endfunction()

#function(check_symbols_in_parallel)
#    internal_check_symbols_in_parallel(parallel_success ${ARGN})
#    if(NOT parallel_success)
#        cmake_parse_arguments(ARG "" "VAR_PREFIX;VAR_SUFFIX" "HEADERS;SYMBOLS" ${ARGN})
#        foreach(symbol IN LISTS ARG_SYMBOLS)
#            string(MAKE_C_IDENTIFIER "${symbol}" varname_core)
#            string(TOUPPER "${varname_core}" varname_core)
#            set(varname "${ARG_VAR_PREFIX}${varname_core}${ARG_VAR_SUFFIX}")
#            if(NOT DEFINED "${varname}" AND NOT DEFINED CACHE{${varname}})
#                list(APPEND symbols ${symbol})
#            endif()
#            check_symbol_exists("${symbol}" "${ARG_HEADERS}" ${varname})
#        endforeach()
#    endif()
#endfunction()
